# Generated by Django 4.1.4 on 2022-12-20 16:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('captio', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('no_of_like', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_image'),
        ),
    ]
